//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefPrototypeAPI_v5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_incident
    {
        public int game_incident_id { get; set; }
        public Nullable<int> game_id { get; set; }
        public string incident_type { get; set; }
        public Nullable<int> player_id { get; set; }
        public Nullable<decimal> incident_time { get; set; }
    }
}
