//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefPrototypeAPI_v5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public int player_id { get; set; }
        public Nullable<int> team_id { get; set; }
        public string player_firstname { get; set; }
        public string player_lastname { get; set; }
        public Nullable<int> player_number { get; set; }
    }
}
