//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefPrototypeAPI_v5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class team
    {
        public int team_id { get; set; }
        public string team_name { get; set; }
        public string team_coach_first_name { get; set; }
        public string team_coach_last_name { get; set; }
    }
}
